# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  # requires AZURE_API_CREDENTIALS environment variable (secret)
  - template: post-process-work-items.yml
    parameters:
        organization: 'rpereira0294'
        project_name: 'Test%20Project'
        azure_base_directory: 'https://dev.azure.com'
        work_item_id_to_link: '2206'
        user_to_assign: 'aad.NTIyZjcwZDYtZTlmNy03M2IwLWExZTktOWY1NzI2YTUwODlm'  #user descriptor
        tag_value_to_filter_issues: 'Build_20383219'
