# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "0 0 * * *"
  displayName: Daily Midnight Build
  branches:
    include:
    - master

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Veracode Flaw Importer Ricardo@3
    inputs:
      ConnectionDetailsSelection: 'Service Connection'
      AnalysisService: 'Veracode - New'
      failBuildIfFlawImporterFails: true
      veracodeAppProfile: 'Verademo ADO'
      sandboxName: 
      scanType: 'Dynamic, Static, SCA'
      importType: 'All Unmitigated Flaws'
      workItemType: 'Bug'
      addDueDateBasedOnGracePeriods: true
      area: '$(system.teamProject)'
      overwriteAreaPathInWorkItemsOnImport: true
      iterationPath: '$(system.teamProject)'
      addCustomTag: 'VeracodeFindingsNew-$(build.buildNumber)'
      flawImportLimit: '1000'

  # requires AZURE_API_CREDENTIALS environment variable (secret)
  - template: post-process-work-items.yml
    parameters:
        organization: 'rpereira0294'
        project_name: 'Test Project'
        azure_base_directory: 'https://dev.azure.com'
        work_item_id_to_link: '2206'
        user_to_assign: 'aad.NTIyZjcwZDYtZTlmNy03M2IwLWExZTktOWY1NzI2YTUwODlm'  #user descriptor
        tag_value_to_filter_issues: 'VeracodeFindingsNew-$(build.buildNumber)'
